### ISSUE TITLE
How to process all ports as features

### ISSUE THREAD

**Issue by alshaboti** [CyberReboot/NetworkML#80]
The current way that ports are processed as features is by limiting port number < `config['max port']` [here](https://github.com/Lab41/PoseidonML/blob/09f55d346411fe1147d4c50c8d330a7bf65f5b48/NodeClassifier/utils/featurizer.py#L29) with is `1024` by default. 

Based on this [paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8116438), IoT devices are using ports numbers greater than 1024. 

Ideally, all ports that are used should be used as features. However, set `max port=65535` will create a huge feature vector where most of its value is zeros. 

What I am proposing is to use two lists during the training (`ports_list` and `ports_freq`). Such that `ports_list` contains only the ports witnessed in the dataset and `ports_freq` counts its frequency. 

What do you think?

**Comment by alshaboti** [comment]
@gregs5 - You are right learning from server/services ports is what we are looking for not the emphemeral ports. 
That paper (http://www2.ee.unsw.edu.au/~vijay/pubs/conf/17infocom.pdf) is the one that you gave me the link for its dataset before :). It shows (in TABLEI) that ten IoT devices use services with ports > 1024 (actual service distination ports not empherals).

**Comment by cglewis** [comment]
@alshaboti I think your proposal makes sense - I'd be happy to review a PR with the proposed changes if you'd like to cook something up. thanks!

**Comment by cglewis** [comment]
Since the ML results and vector representations are already stored in Redis, that seems like a good place for this list as well?

**Comment by lilchurro** [comment]
@alshaboti An overhaul of the featurizer might be in order. I've opened issue #84 to explain the rationale behind this. Until that's actually implemented, though, I think your solution is probably reasonable... though I would caution that if you could code the ingesting of ports and their counts so that users and subsequent coders don't have to manually keep track of the ordering, that would be ideal. Perhaps use of a dictionary that could then be flattened/standardized for use by other functions?

**Comment by cglewis** [comment]
So thinking about this a bit more, since the list will be needed for both training and evaluation/testing it probably doesn’t make sense to use Redis, since it won’t necessarily be the same instance at training and evaluation times.  It probably makes more sense to include it in the pickled model, or possibly as a supplemental file alongside the model.  Open to ideas there.

**Comment by cglewis** [comment]
@alshaboti open to seeing what that looks like. it might work?

**Comment by cglewis** [comment]
This is now doable using the `featurizer` to create functions of whatever ports you want as features.
